//
//	DO NOT EDIT THIS FILE
//	IT IS AUTO GENERATED BY MGC
//	TEMPLATE: gomod.template
//
// github.com/MagaluCloud/mgc-sdk-go v0.3.45

module gfcli

go 1.24.2

require (
	github.com/MagaluCloud/mgc-sdk-go v0.3.45
	github.com/fatih/color v1.16.0
	github.com/spf13/cobra v1.9.1
	github.com/spf13/pflag v1.0.6
)

require (
	github.com/inconshreveable/mousetrap v1.1.0 // indirect
	github.com/mattn/go-colorable v0.1.13 // indirect
	github.com/mattn/go-isatty v0.0.20 // indirect
	golang.org/x/sys v0.14.0 // indirect
	gopkg.in/yaml.v3 v3.0.1 // indirect
)
